# Generated by Django 3.1.5 on 2021-01-11 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=4)),
                ('production_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='rentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapi.movie')),
            ],
        ),
    ]
