# Generated by Django 3.1.5 on 2021-01-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapi', '0002_auto_20210112_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentals',
            old_name='movie_name',
            new_name='movie_id',
        ),
    ]
